spring:
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:${DATABASE_PATH}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  flyway:
    baseline-on-migrate: true
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.ws: DEBUG
server:
  hostname: localhost
  port: ${PORT:8080}
mail:
  server:
    host: smtp.beget.com
    port: 25
    username: test@bolshakov.pro
    password: ${hidden.email.password}