//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.29 at 12:26:30 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bolshakov.pro/geekbrains/springleveltwo/shop/ws/greeting", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pro.bolshakov.geekbrains.springleveltwo.shop.ws.greeting;
